# Generated by Django 3.1.6 on 2021-02-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210203_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='category',
            field=models.CharField(choices=[('EC', 'Education'), ('HL', 'Health'), ('FM', 'Family'), ('TN', 'Technology'), ('EN', 'Economy'), ('RL', 'Religion ')], default='TN', max_length=50),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='status',
            field=models.CharField(choices=[('D', 'Draft '), ('P', 'Published ')], default='P', max_length=50),
        ),
    ]
