# Generated by Django 3.1.6 on 2021-02-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postlike_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='category',
            field=models.CharField(choices=[('E', 'Education'), ('H', 'Health'), ('F', 'Family'), ('T', 'Technology'), ('EC', 'Economy'), ('R', 'Religion ')], default='T', max_length=50),
        ),
    ]
